spring:
    application:
        name: Blog Application

    datasource:
        driver-class-name: org.postgresql.Driver

        url: ${BLOG_APP_DB_URL}
        username: ${BLOG_APP_DB_USERNAME}
        password: ${BLOG_APP_DB_PASSWORD}

upload.images.dir: C:/Users/79185/IdeaProjects/blog-app/src/main/webapp/images/

server:
    servlet:
        context-path: /blog-app

---
spring:
    config:
        activate:
            on-profile: test # ?????????? ???? ???? ?????? ??? ??????? "test"

    datasource:
        url: ${BLOG_APP_TEST_DB_URL}
        username: ${BLOG_APP_DB_USERNAME}
        password: ${BLOG_APP_DB_PASSWORD}



